home:
  description_link: "https://www.railstutorial.org/"
  image_link: "https://rubyonrails.org/"
help:
  help_page_link: "http://www.railstutorial.org/help"
  help_book_link: "http://www.railstutorial.org/book"
about:
  about_screencast: "http://screencasts.railstutorial.org/"
contact:
  contact_page_link: "https://www.railstutorial.org/contact"

max_length_name: 50
max_length_email: 250
min_length_password: 6
items_per_page: 10
valid_email_regex: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
value_create: "1"
time_expired: 2
